const exams = [
    {
      name: "平成21年春期",
      pm1Len: 4,
      pm2Len: 2,
      link:"21_haru",
    },
    {
      name: "平成21年秋期",
      pm1Len: 4,
      pm2Len: 2,
      link:"21_aki",
    },
    {
      name: "平成22年春期",
      pm1Len: 4,
      pm2Len: 2,
      link:"22_haru",
    },
    {
      name: "平成22年秋期",
      pm1Len: 4,
      pm2Len: 2,
      link:"22_aki",
    },
    {
      name: "平成23年特別",
      pm1Len: 4,
      pm2Len: 2,
      link:"23_toku"
    },
    {
      name: "平成23年秋期",
      pm1Len: 4,
      pm2Len: 2,
      link:"23_aki",
    },
    {
      name: "平成24年春期",
      pm1Len: 4,
      pm2Len: 2,
      link:"24_haru",
    },
    {
      name: "平成24年秋期",
      pm1Len: 4,
      pm2Len: 2,
      link:"24_aki",
    },
    {
      name: "平成25年春期",
      pm1Len: 4,
      pm2Len: 2,
      link:"25_haru",
    },
    {
      name: "平成25年秋期",
      pm1Len: 3,
      pm2Len: 2,
      link:"25_aki",
    },
    {
      name: "平成26年春期",
      pm1Len: 3,
      pm2Len: 2,
      link:"26_haru",
    },
    {
      name: "平成26年秋期",
      pm1Len: 3,
      pm2Len: 2,
      link:"26_aki",
    },
    {
      name: "平成27年春期",
      pm1Len: 3,
      pm2Len: 2,
      link:"27_haru",
    },
    {
      name: "平成27年秋期",
      pm1Len: 3,
      pm2Len: 2,
      link:"27_aki",
    },
    {
      name: "平成28年春期",
      pm1Len: 3,
      pm2Len: 2,
      link:"28_haru",
    },
    {
      name: "平成28年秋期",
      pm1Len: 3,
      pm2Len: 2,
      link:"21_aki",
    },
    {
      name: "平成29年春期",
      pm1Len: 3,
      pm2Len: 2,
      link:"29_haru",
    },
    {
      name: "平成29年秋期",
      pm1Len: 3,
      pm2Len: 2,
      link:"29_aki",
    },
    {
      name: "平成30年春期",
      pm1Len: 3,
      pm2Len: 2,
      link:"30_haru",
    },
    {
      name: "平成30年秋期",
      pm1Len: 3,
      pm2Len: 2,
      link:"30_aki",
    },
    {
      name: "平成31年春期",
      pm1Len: 3,
      pm2Len: 2,
      link:"31_haru",
    },
    {
      name: "令和元年秋期",
      pm1Len: 3,
      pm2Len: 2,
      link:"01_aki",
    },
    {
      name: "令和2年秋期",
      pm1Len: 3,
      pm2Len: 2,
      link:"02_aki",
    },
    {
      name: "令和3年春期",
      pm1Len: 3,
      pm2Len: 2,
      link:"03_haru",
    },
    {
      name: "令和3年秋期",
      pm1Len: 3,
      pm2Len: 2,
      link:"03_aki",
    },
    {
      name: "令和4年春期",
      pm1Len: 3,
      pm2Len: 2,
      link:"04_haru",
    },
    {
      name: "令和4年秋期",
      pm1Len: 3,
      pm2Len: 2,
      link:"04_aki",
    },
    {
      name: "令和5年春期",
      pm1Len: 3,
      pm2Len: 2,
      link:"05_haru",
    },
    {
      name: "令和5年秋期",
      pm1Len: 4,
      pm2Len: 0,
      link:"05_aki",
    },
    {
      name: "令和6年春期",
      pm1Len: 4,
      pm2Len: 0,
      link:"06_haru",
    },
  ];

  export default exams;